#! /usr/bin/bash

shopt -s extglob

hour=$(date +%k)

if   (( $hour >= 3 && $hour <= 11))
then
echo "Good morning$1"
elif (( $hour >= 12 && $hour <= 18))
then
echo "Good afternoon$1"
else
echo "Good evening$1"
fi
